export const steps = [
  "start",
  "chooseAction",
  "transactCrypto",
  "transferMoney",
  "estimateAsset",
  "network",
  "payOptions",
  "charge",
  "enterBankSearchWord",
  "selectBank",
  "enterAccountNumber",
  "continueToPay",
  "enterPhone",
  "sendPayment",
  "confirmTransaction",
  "paymentProcessing",
  "kycInfo",
  "kycReg",
  "thankForKYCReg",
  "supportWelcome",
  "assurance",
  "entreTrxId",
  "makeComplain",
  "completeTransactionId",
  "giftFeedBack",
  "makeReport",
  "reporterName",
  "reporterPhoneNumber",
  "reporterWallet",
  "fraudsterWallet",
  "reportlyNote",
  "reporterFarwell",
] as const;

export type StepId = (typeof steps)[number];
